import Head from "next/head";
import useFetch from "@/hooks/useFetch";
import { Container, Row } from "react-bootstrap";
import CardDesign from "@/components/cardDesign/CardDesign";
import LoadingSpinner from "@/components/loadingSpinner/LoadingSpinner";

export default function Advisor() {
  const { data, loading } = useFetch("/member/Advisor");
  return (
    <>
      <Head>
        <title>Cox&apos;s Bazar Student Forum Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        {loading ? (
          <LoadingSpinner />
        ) : (
          <>
            <div className="headerTitle mt-5">
              <h3 class="headerTitleMain">উপদেষ্টামন্ডলী</h3>
            </div>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                {data?.data?.map((item) => (
                  <CardDesign key={item.serial} item={item} />
                ))}
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
