import Head from "next/head";
import useFetch from "@/hooks/useFetch";
import { Col, Container, Row, Table } from "react-bootstrap";
import LoadingSpinner from "@/components/loadingSpinner/LoadingSpinner";

export default function Home() {
  const { data, loading } = useFetch("/expre");
  return (
    <>
      <Head>
        <title>Cox&apos;s Bazar Student Forum Expre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        {loading ? (
          <LoadingSpinner />
        ) : (
          <>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                <Col lg={8} md={10} sm={12} className="mx-auto">
                  <div className="headerTitle">
                    <h3 class="headerTitleMain">সভাপতিবৃন্দ</h3>
                  </div>
                  <Table striped bordered hover responsive>
                    <thead>
                      <tr>
                        <th>নাম</th>
                        <th>হতে</th>
                        <th>পযর্ন্ত</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data?.data1?.map((president) => (
                        <tr key={president?.id}>
                          <td>{president?.name}</td>
                          <td>{president?.date1}</td>
                          <td>{president?.date2}</td>
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </Col>
              </Row>
              <Row className="my-5">
                <Col lg={8} md={10} sm={12} className="mx-auto">
                  <div className="headerTitle">
                    <h3 class="headerTitleMain">সাধারণ সম্পাদক বৃন্দ</h3>
                  </div>
                  <Table striped bordered hover responsive>
                    <thead>
                      <tr>
                        <th>নাম</th>
                        <th>হতে</th>
                        <th>পযর্ন্ত</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data?.data2?.map((president) => (
                        <tr key={president?.id}>
                          <td>{president?.name}</td>
                          <td>{president?.date1}</td>
                          <td>{president?.date2}</td>
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </Col>
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
