import Head from "next/head";
import { Inter } from "next/font/google";
import useFetch from "@/hooks/useFetch";
import { Container, Row } from "react-bootstrap";
import CardDesign from "@/components/cardDesign/CardDesign";
import { useState } from "react";
import Pagination from "@/components/pagination/Pagination";

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const [coursesPerPage] = useState(15);

  const { data, loading } = useFetch("/member/csfdu/General");

  // Pagination er jonno
  const indexOfLastPost = currentPage * coursesPerPage;
  const indexOfFirstPost = indexOfLastPost - coursesPerPage;

  return (
    <>
      <Head>
        <title>Cox&apos;s Bazar Student Forum General</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./csfdu.jpeg" />
      </Head>
      <main>
        {loading ? (
          <div className="loadingContainer">
            <img src="./loading.gif" alt="" className="loadingGif" />
          </div>
        ) : (
          <>
            <div className="headerTitle mt-5">
              <h3 class="headerTitleMain">সাধারণ সদস্য</h3>
            </div>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                {data?.data?.map((item) => (
                  <CardDesign key={item.serial} item={item} />
                ))}
              </Row>
              {/* <Pagination
                coursesPerPage={coursesPerPage}
                totalPosts={data?.data?.length}
                setCurrentPage={setCurrentPage}
              /> */}
            </Container>
          </>
        )}
      </main>
    </>
  );
}
