/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import President from "@/components/home/president/President";
import useFetch from "@/hooks/useFetch";
import HomeAdvisor from "@/components/home/homeAdvisor/HomeAdvisor";
import HomeCountUp from "@/components/home/homeCountUp/HomeCountUp";
import CarouselBanner from "@/components/home/carouselBanner/CarouselBanner";
import LoadingSpinner from "@/components/loadingSpinner/LoadingSpinner";
import { TITLE } from "@/utils/api";
import Advertise from "@/components/home/advertise/Advertise";
import HomeUnionMember from "@/components/home/homeUnionMember/HomeUnionMember";
import HomeWelcomeMessage from "@/components/home/homeWelcomeMessage/HomeWelcomeMessage";
import HomeNotice from "@/components/home/homeNotice/HomeNotice";
import SliderSkeleton from "@/components/loader/SliderSkeleton";
import MemberSkeleton from "@/components/loader/MemberSkeleton";
import FeaturesSkeleton from "@/components/loader/FeaturesSkeleton";

export default function Home() {
  const { data, loading } = useFetch("/home");
  const { data: welcomeMessage, loading: loadingMessage } = useFetch(
    "/Organization_message"
  );
  const { data: notices, loading: noticeLoading } = useFetch("/notice");
  return (
    <>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        <>
          {loading ? (
            <SliderSkeleton />
          ) : (
            <CarouselBanner data={data} loading={loading} />
          )}

          <HomeUnionMember />

          {loading ? (
            <FeaturesSkeleton />
          ) : (
            <>
              <HomeWelcomeMessage welcomeMessage={welcomeMessage} />
              <President data={data} loading={loading} />
            </>
          )}

          <Advertise />
          {loading ? (
            <MemberSkeleton />
          ) : (
            <HomeCountUp data={data} loading={loading} />
          )}

          {noticeLoading ? (
            <MemberSkeleton />
          ) : (
            <HomeNotice noticeData={notices?.data} />
          )}
        </>
      </main>
    </>
  );
}
