/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import President from "@/components/home/president/President";
import useFetch from "@/hooks/useFetch";
import HomeAdvisor from "@/components/home/homeAdvisor/HomeAdvisor";
import HomeCountUp from "@/components/home/homeCountUp/HomeCountUp";
import CarouselBanner from "@/components/home/carouselBanner/CarouselBanner";

export default function Home() {
  const { data, loading } = useFetch("/home/csfdu");
  return (
    <>
      <Head>
        <title>Cox&apos;s Bazar Student Forum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./csfdu.jpeg" />
      </Head>
      <main>
        {loading ? (
          <div className="loadingContainer">
            <img src="./loading.gif" alt="" className="loadingGif" />
          </div>
        ) : (
          <>
            <CarouselBanner data={data} loading={loading} />
            <HomeCountUp data={data} loading={loading} />
            <President data={data} loading={loading} />
            <HomeAdvisor data={data} loading={loading} />
          </>
        )}
      </main>
    </>
  );
}
